name: Staging Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: npm install
      run: npm install

    - name: npm run bundle
      run: npm run bundle
      
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://43.255.154.8
        ftp-username: nikunjnasit@codetrinity.com
        ftp-password: ${{ secrets.FTP_PASSWORD }}
